export const hotel = {
  name: "PK Group Residency",
  tagline: "Premium AC & Non-AC Rooms",
  rating: "4.9",
  ratingCount: "128",
  location: "Palakkad, Kerala",
  address: "Agali, Attappadi, Palakkad, Kerala - 678581",
  phone: "+919544707888",
  phoneRaw: "+919544707888",
  whatsapp: "https://wa.me/919544707888?text=Hello%2C%20I%20would%20like%20to%20inquire%20about%20booking%20a%20room%20at%20PK%20Group%20Residency.",
  instagram: "https://www.instagram.com/pk_group_residency/",
  website: "https://pkgroupresidency.com",
  maps: "https://www.google.com/maps/search/?api=1&query=PK+Group+Residency+Mukkali+Kerala",
  reviews: "https://www.google.com/search?q=PK+Group+Residency+Mukkali+Kerala+Reviews",
  email: "info@pkgroupresidency.com",
};
